export const speciesData = [
    { commonName: "Lusitanian Cownose Ray", scientificName: "Rhinoptera marginata" },
    { commonName: "Spiny butterfly Ray", scientificName: "Gymnura altavela" },
    { commonName: "Guitarfish", scientificName: "Guitarfish indet." },
    { commonName: "Blackchin Guitarfish", scientificName: "Glaucostegus cemiculus" },
    { commonName: "Common Guitarfish", scientificName: "Rhinobatos rhinobatos" },
    { commonName: "Small Spotted Catshark", scientificName: "Scyliorhinus canicula" },
    { commonName: "Blackmouth Catshark", scientificName: "Galeus melastomus" },
    { commonName: "Spotted Torpedo", scientificName: "Torpedo marmorata" },
    { commonName: "Great Torpedo Ray", scientificName: "Tetronarce nobiliana" },
    { commonName: "Ocellate Torpedo", scientificName: "Torpedo torpedo" },
    { commonName: "Torpedo Ray", scientificName: "Torpedo spp." },
    { commonName: "Common Eagle Ray", scientificName: "Myliobatis aquila" },
    { commonName: "Common Eagle Ray", scientificName: "Aetomylaeus bovinus" },
    { commonName: "Stingray", scientificName: "Dasyatis spp." },
    { commonName: "Blue Stingray", scientificName: "Dasyatis marmorata" },
    { commonName: "common stingray", scientificName: "Dasyatis pastinaca" },
    { commonName: "Tortonese's Stingray", scientificName: "Dasyatis tortonesei" },
    { commonName: "Pelagic Stingray", scientificName: "Pteroplatytrygon violacea" },
    { commonName: "Roughtail Stingray", scientificName: "Bathytoshia centroura" },
    { commonName: "Reticulate Whipray", scientificName: "Himantura uarnak" },
    { commonName: "Angular Rough Shark", scientificName: "Oxynotus centrina" },
    { commonName: "Little Sleeper Shark", scientificName: "Somniosus rostratus" },
    { commonName: "Rabbitfish", scientificName: "Chimaera monstrosa" },
    { commonName: "Giant Devil Ray", scientificName: "Mobula mobular" },
    { commonName: "Requiem shark", scientificName: "Carcharhinus spp." },
    { commonName: "Oceanic white-tip", scientificName: "Carcharhinus longimanus" },
    { commonName: "Bignose Shark", scientificName: "Carcharhinus altimus" },
    { commonName: "Blue Shark", scientificName: "Prionace glauca" },
    { commonName: "Sandbar Shark", scientificName: "Carcharhinus plumbeus" },
    { commonName: "Basking Shark", scientificName: "Cetorhinus maximus" },
    { commonName: "Dusky Shark", scientificName: "Carcharhinus obscurus" },
    { commonName: "Spinner Shark", scientificName: "Carcharhinus brevipinna" },
    { commonName: "Blacktip Shark", scientificName: "Carcharhinus limbatus" },
    { commonName: "Small-tooth Sand Tiger Shark", scientificName: "Odontaspis ferox" },
    { commonName: "Sand Tiger", scientificName: "Carcharias taurus" },
    { commonName: "Whithound", scientificName: "Galeorhinus galeus" },
    { commonName: "Common Smoothhound", scientificName: "Mustelus mustelus" },
    { commonName: "Blackspotted Smoothhound", scientificName: "Mustelus punctulatus" },
    { commonName: "Bigeye Thresher Shark", scientificName: "Alopias superciliosus" },
    { commonName: "Common Thresher Shark", scientificName: "Alopias vulpinus" },
    { commonName: "Round Fantail Stingray", scientificName: "Taeniurops grabatus" },
    { commonName: "Smoothback Angel Shark", scientificName: "Squatina oculata" },
    { commonName: "Angel Shark", scientificName: "Squatina squatina" },
    { commonName: "Sawback Angelshark", scientificName: "Squatina aculeata" },
    { commonName: "Smalltooth Sawfish", scientificName: "Pristis pectinata" },
    { commonName: "Porbeagle", scientificName: "Lamna nasus" },
    { commonName: "Shortfin Mako", scientificName: "Isurus oxyrinchus" },
    { commonName: "Great White Shark", scientificName: "Carcharodon carcharias" },
    { commonName: "Smooth Hammerhead", scientificName: "Sphyrna zygaena" },
    { commonName: "Longnose Spurdog", scientificName: "Squalus blainville" },
    { commonName: "Gulper Shark", scientificName: "Centrophorus granulosus" },
    { commonName: "Piked Dogfish", scientificName: "Squalus acanthias" },
    { commonName: "Velvet Belly Lanternshark", scientificName: "Etmopterus spinax" },
    { commonName: "Kitefin Shark", scientificName: "Dalatias licha" },
    { commonName: "Sharpnose Sevengill Shark", scientificName: "Heptranchias perlo" },
    { commonName: "Bluntnose Sixgill Shark", scientificName: "Hexanchus griseus" },
    { commonName: "Undulate Ray", scientificName: "Raja undulata" },
    { commonName: "Brown Skate", scientificName: "Raja miraletus" },
    { commonName: "Sharpnose Skate", scientificName: "Dipturus oxyrinchus" },
    { commonName: "Rough Ray", scientificName: "Raja radula" },
    { commonName: "Starry Ray", scientificName: "Raja asterias" },
    { commonName: "Thornback Skate", scientificName: "Raja clavata" },
    { commonName: "Spotted Ray", scientificName: "Raja montagui" },
    { commonName: "Blue Skate", scientificName: "Dipturus batis" },
    { commonName: "Bottlenose Skate", scientificName: "Rostroraja alba" },
    { commonName: "Shagreen Ray", scientificName: "Leucoraja fullonica" },
    { commonName: "Blonde Ray", scientificName: "Raja brachyura" },
    { commonName: "Bramble Shark", scientificName: "Echinorhinus brucus" },
    { commonName: "Sandy Skate", scientificName: "Leucoraja circularis" },
    { commonName: "Cuckoo Skate", scientificName: "Leucoraja naevus" },
    { commonName: "Speckled Skate", scientificName: "Raja polystigma" },
    { commonName: "Nursehound", scientificName: "Scyliorhinus stellaris" }
];
